name: tictactoe
description: A Tic tac toe game.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  modal_bottom_sheet: ^2.0.1

  mobx: ^2.0.6
  flutter_mobx: ^2.0.6+1

  get_it: ^7.2.0

  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.7
  build_runner:

flutter:
  uses-material-design: true
